# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: qwilco/docker-python:3.5.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          environment:
          # Have pipenv install the venv to the local .venv directory instead of to the user's home directory.
          - PIPENV_VENV_IN_PROJECT: 1
          command: make init

      - save_cache:
          paths:
            - /root/repo/.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      # run tests!
      - run:
          name: run tests
          environment:
          - PIPENV_VENV_IN_PROJECT: 1
          command: make ci

      - store_test_results:
          path: /root/repo/reports

#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
